import { Poppins, Inter, Google_Sans_Flex } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
 
})
const inter = Inter({
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
 
})
const sans = Google_Sans_Flex({
  variable: "--font-google-sans",
 weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
 
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${poppins.variable} ${inter.variable} ${sans.variable}`}
    >
      <body className={`min-h-full flex flex-col`}>
        <div>
          <Navbar/>
        </div>
        <main>

        {children}
        </main>
        </body>
    </html>
  );
}
